package javaVersion.info; public class asdasdasd extends SellerInfo { public asdasdasd() { super( "#12222", "asdasdasd");} public int updateByUserInfo(UserInfo userInfo) { int hour = userInfo.getHour();
if (hour == 0) varList.set(0, "");
if (hour == 1) varList.set(0, "");
if (hour == 2) varList.set(0, "");
if (hour == 3) varList.set(0, "");
if (hour == 4) varList.set(0, "");
if (hour == 5) varList.set(0, "");
if (hour == 6) varList.set(0, "");
if (hour == 7) varList.set(0, "");
if (hour == 8) varList.set(0, "");
if (hour == 9) varList.set(0, "");
if (hour == 10) varList.set(0, "");
if (hour == 11) varList.set(0, "");
if (hour == 12) varList.set(0, "");
if (hour == 13) varList.set(0, "");
if (hour == 14) varList.set(0, "");
if (hour == 15) varList.set(0, "");
if (hour == 16) varList.set(0, "");
if (hour == 17) varList.set(0, "");
if (hour == 18) varList.set(0, "");
if (hour == 19) varList.set(0, "");
if (hour == 20) varList.set(0, "");
if (hour == 21) varList.set(0, "");
if (hour == 22) varList.set(0, "");
if (hour == 23) varList.set(0, "");
return 0;
} }